include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - close_sinks
    - unawaited_futures
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
#   plugins:
#     - custom_lint
