name: araidashisan
description: "洗い出しさん"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  rxdart: ^0.27.7
  get_it: ^7.7.0
  logger: ^2.3.0
  yaml: ^3.1.2
  web: ^1.0.0
  csv: ^6.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  custom_lint: ^0.6.4
  build_runner: ^2.4.12
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  generate: true
